\begin{code}[hide]

open import Agda.Primitive
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma
open import Agda.Builtin.Equality

-- composition
_∘_ : {A : Set} {B : A → Set} {C : {x : A} → B x → Set}
      (f : {x : A}(y : B x) → C y) (g : (x : A) → B x) (x : A) → C (g x)
(f ∘ g) x = f (g x)

-- binary product
_×_ : {m n : Level} → Set m → Set n → Set (m ⊔ n)
A × B = Σ A (λ _ → B)

π₁ : {A B : Set} → A × B → A
π₁ = fst

π₂ : {A B : Set} → A × B → B
π₂ = snd
\end{code}

\paragraph{Syntax.}
%
We consider simple types over a countable set of base types: 
\begin{code}
-- base types
T : Set 
T = Nat

-- simple types
data 𝓣 : Set where 
  θ : T → 𝓣
  υ : 𝓣
  _⋆_ : 𝓣 → 𝓣 → 𝓣
  _⇒_ : 𝓣 → 𝓣 → 𝓣
\end{code}

Typing contexts are inductively generated by context extension from an empty
context:
%
\begin{code}
-- typing contexts
data 𝔽↓ : Set →  Set where
  · : {𝓧 : Set} → 𝔽↓ 𝓧
  _::_ : {𝓧 : Set} → 𝔽↓ 𝓧 → 𝓧 → 𝔽↓ 𝓧
\end{code}
%
We then have a family of variable indices given as follows:
%
\begin{code}
-- variable indices
data V : {𝓧 : Set} → 𝓧 → 𝔽↓ 𝓧 → Set where
  • : {𝓧 : Set} {α : 𝓧} {Γ : 𝔽↓ 𝓧} → V α (Γ :: α) 
  ↑ : {𝓧 : Set} {α β : 𝓧} {Γ : 𝔽↓ 𝓧} → V β Γ → V β (Γ :: α)
\end{code}
%
for which context renamings are considered:
%
\begin{code}
-- context renamings
𝔽↓₀ : (𝓣 : Set) → 𝔽↓ 𝓣 × 𝔽↓ 𝓣 → Set
𝔽↓₀ 𝓣 (Δ , Γ ) = {α : 𝓣} → V α Δ → V α Γ
\end{code}

The abstract syntax of simply typed terms is implemented by the inductive
family below:
\begin{code}
-- simply typed terms
data 𝓛 : 𝓣 → 𝔽↓ 𝓣 → Set where
  var : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → V α Γ → 𝓛 α Γ
  unit : {Γ : 𝔽↓ 𝓣} → 𝓛 υ Γ
  pair : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 α Γ → 𝓛 β Γ → 𝓛 (α ⋆ β) Γ
  fst₀ : {α β : 𝓣}  {Γ : 𝔽↓ 𝓣} → 𝓛 (α ⋆ β) Γ → 𝓛 α Γ
  snd₀ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 (α ⋆ β) Γ → 𝓛 β Γ
  abs : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 β (Γ :: α ) → 𝓛 (α ⇒ β) Γ
  app : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 (α ⇒ β) Γ → 𝓛 α Γ → 𝓛 β Γ
\end{code}
%
Analogously, the abstract syntax of neutral and normal terms is implemented
by the following mutually-inductive families:
%
\begin{code}
-- neutral and normal terms
mutual
  data 𝓜 : 𝓣 → 𝔽↓ 𝓣 → Set where
    varₘ : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → V α Γ → 𝓜 α Γ
    fstₘ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓜 (α ⋆ β) Γ → 𝓜 α Γ
    sndₘ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓜 (α ⋆ β) Γ → 𝓜 β Γ
    appₘ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓜 (α ⇒ β) Γ → 𝓝 α Γ → 𝓜 β Γ
    
  data 𝓝 : 𝓣 → 𝔽↓ 𝓣 → Set where
    norm : {i : T} {Γ : 𝔽↓ 𝓣} → 𝓜 (θ i) Γ → 𝓝 (θ i) Γ
    unitₙ : {Γ : 𝔽↓ 𝓣} → 𝓝 υ Γ
    pairₙ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓝 α Γ → 𝓝 β Γ → 𝓝 (α ⋆ β) Γ
    absₙ : {α β : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓝 β (Γ :: α) → 𝓝 (α ⇒ β) Γ
\end{code}
%
For these we need provide their presheaf actions:
%
\begin{code}
-- neutral and normal presheaf actions
mutual
  _[_]ₘ : {α : 𝓣} {Δ Γ : 𝔽↓ 𝓣} → 𝓜 α Δ → 𝔽↓₀ 𝓣( Δ , Γ ) → 𝓜 α Γ
  varₘ x [ ρ ]ₘ = varₘ ( ρ x )
  fstₘ m [ ρ ]ₘ = fstₘ ( m [ ρ ]ₘ )
  sndₘ m [ ρ ]ₘ = sndₘ ( m [ ρ ]ₘ )
  appₘ m n [ ρ ]ₘ = appₘ ( m [ ρ ]ₘ ) ( n [ ρ ]ₙ )

  _[_]ₙ : {α : 𝓣} {Δ Γ : 𝔽↓ 𝓣} → 𝓝 α Δ → 𝔽↓₀ 𝓣( Δ , Γ ) → 𝓝 α Γ
  norm m [ ρ ]ₙ = norm( m [ ρ ]ₘ ) 
  unitₙ [ ρ ]ₙ = unitₙ
  pairₙ n₁ n₂ [ ρ ]ₙ = pairₙ ( n₁ [ ρ ]ₙ ) ( n₂ [ ρ ]ₙ )
  absₙ n [ ρ ]ₙ = absₙ ( n [ lift ρ ]ₙ )
                  where
                    lift : {α : 𝓣} {Δ Γ : 𝔽↓ 𝓣} → 𝔽↓₀ 𝓣( Δ , Γ ) → 𝔽↓₀ 𝓣( Δ :: α , Γ :: α )
                    lift _ • = •
                    lift ρ (↑ x) = ↑(ρ x)
\end{code}

\medskip
\mysubparagraph{Semantics.}
%
We implement the presheaf semantics of types induced by the interpretation of
base types as neutral terms.
%
\begin{code}
-- type semantics
𝓢⟦_⟧ : 𝓣 → 𝔽↓ 𝓣 → Set
𝓢⟦ θ i ⟧ Γ = 𝓜 (θ i) Γ
𝓢⟦ υ ⟧ _ = ⊤ 
𝓢⟦ α ⋆ β ⟧ Γ = (𝓢⟦ α ⟧ Γ) × (𝓢⟦ β ⟧ Γ)
𝓢⟦ α ⇒ β ⟧ Γ = {Δ : 𝔽↓ 𝓣} → 𝔽↓₀ 𝓣( Γ , Δ ) → 𝓢⟦ α ⟧ Δ → 𝓢⟦ β ⟧ Δ

_[_] : {α : 𝓣} {Δ Γ : 𝔽↓ 𝓣} → 𝓢⟦ α ⟧ Δ → 𝔽↓₀ 𝓣( Δ , Γ ) → 𝓢⟦ α ⟧ Γ
_[_] {θ _} = _[_]ₘ
_[_] {υ} = _
_[_] {_ ⋆ _} ( x₁ , x₂ ) ρ = ( x₁ [ ρ ] , x₂ [ ρ ] )
_[_] {_ ⇒ _} f ρ ρ′ = f (ρ′ ∘ ρ)
\end{code}

The semantic interpretation of terms follows:
%
\begin{code}
-- term semantics
Π : 𝔽↓ 𝓣 → (𝓣 → 𝔽↓ 𝓣 → Set) → 𝔽↓ 𝓣 → Set
Π · _ _ = ⊤
Π (Γ :: α) P Δ = (Π Γ P Δ) × (P α Δ)

𝓼⟦_⟧ : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 α Γ → {Δ : 𝔽↓ 𝓣} → Π Γ 𝓢⟦_⟧ Δ → 𝓢⟦ α ⟧ Δ
𝓼⟦ var x ⟧ ε = ε ≪ x ≫
             where
               _≪_≫ : {α : 𝓣} {Γ Δ : 𝔽↓ 𝓣} → Π Γ 𝓢⟦_⟧ Δ → V α Γ → 𝓢⟦ α ⟧ Δ
               ε ≪ • ≫ = π₂ ε
               ε ≪ ↑ x ≫ = π₁ ε ≪ x ≫
𝓼⟦ unit ⟧ _ = _
𝓼⟦ pair t₁ t₂ ⟧ ε = ( 𝓼⟦ t₁ ⟧ ε , 𝓼⟦ t₂ ⟧ ε )
𝓼⟦ fst₀ t ⟧ ε = π₁ ( 𝓼⟦ t ⟧ ε ) 
𝓼⟦ snd₀ t ⟧ ε = π₂ ( 𝓼⟦ t ⟧ ε ) 
𝓼⟦ abs t ⟧ ε f x = 𝓼⟦ t ⟧ ( ε [ f ]ₚ , x )
                 where
                   _[_]ₚ : {Ξ Δ Γ : 𝔽↓ 𝓣} → Π Ξ 𝓢⟦_⟧ Δ → 𝔽↓₀ 𝓣( Δ , Γ ) → Π Ξ 𝓢⟦_⟧ Γ
                   _[_]ₚ {·} = _
                   _[_]ₚ {_ :: _} ( ε , x ) ρ = ( ε [ ρ ]ₚ , x [ ρ ] )
𝓼⟦ app t₁ t₂ ⟧ ε = 𝓼⟦ t₁ ⟧ ε (λ x → x) ( 𝓼⟦ t₂ ⟧ ε )
\end{code}

\medskip
\paragraph{Normalisation by evaluation.}
%
The unquote and quote functions are implemented:
\begin{code}
-- unquote and quote
mutual
  u : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓜 α Γ → 𝓢⟦ α ⟧ Γ
  u {θ _} m = m
  u {υ} _ = _
  u {_ ⋆ _} m = ( u (fstₘ m) , u (sndₘ m) )
  u {_ ⇒ _} m ρ x = u ( appₘ (m [ ρ ]ₘ) (q x) )
  
  q : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓢⟦ α ⟧ Γ → 𝓝 α Γ
  q {θ _} = norm
  q {υ} _ = unitₙ
  q {_ ⋆ _} (x₁ , x₂) = pairₙ (q x₁) (q x₂) 
  q {_ ⇒ _} f = absₙ( q( f ↑ (u (varₘ •)) ) )
\end{code}

Finally, the normalisation function is:
%
\begin{code}
-- nbe
nf : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 α Γ → 𝓝 α Γ
nf t = q ( 𝓼⟦ t ⟧ ( Π₀ (u ∘ varₘ) xs ) )
     where
       Π₀ : (f : {α : 𝓣} {Δ : 𝔽↓ 𝓣} → V α Δ → 𝓢⟦_⟧ α Δ) {Γ Δ : 𝔽↓ 𝓣} → Π Γ V Δ → Π Γ 𝓢⟦_⟧ Δ
       Π₀ _ {·} _ = _
       Π₀ f {_ :: _} ( xs , x ) = ( Π₀ f xs , f x )
       
       xs : {Γ : 𝔽↓ 𝓣} → Π Γ V Γ
       xs {·} = _
       xs {_ :: _} = (  xs [ ↑ ]ᵥ , • )
                 where
                   _[_]ᵥ : {Ξ Δ Γ : 𝔽↓ 𝓣} → Π Ξ V Δ → 𝔽↓₀ 𝓣( Δ , Γ ) → Π Ξ V Γ
                   _[_]ᵥ {·} = _
                   _[_]ᵥ {_ :: _} ( xs , x ) ρ = ( xs [ ρ ]ᵥ , ρ x )
\end{code}

\begin{code}[hide]
mutual
  tm : {α : 𝓣} → {Γ : 𝔽↓ 𝓣} → 𝓜 α Γ → 𝓛 α Γ
  tm (varₘ m) = var m
  tm (fstₘ m) = fst₀ (tm m)
  tm (sndₘ m) = snd₀ (tm m)
  tm (appₘ m n) = app (tm m) (tn n)  

  tn : {α : 𝓣}  → {Γ : 𝔽↓ 𝓣} → 𝓝 α Γ → 𝓛 α Γ
  tn (norm m) = tm m
  tn unitₙ = unit
  tn (pairₙ n₁ n₂) = pair (tn n₁) (tn n₂)
  tn (absₙ n) = abs (tn n)

lnf : {α : 𝓣} {Γ : 𝔽↓ 𝓣} → 𝓛 α Γ → 𝓛 α Γ
lnf = tn ∘ nf

-- examples
B0 : 𝓣
B0 = θ zero

v1 : 𝓛 B0 ((· :: B0) :: B0)
v1 = var • 

v2 : 𝓛 B0 ((· :: B0) :: B0)
v2 = var(↑ •)

t1 : 𝓛 (B0 ⋆ B0) ((· :: B0) :: B0)
t1 =  pair v1 ( fst₀ ( pair v2 v1 ) )

checka : lnf t1 ≡ pair v1 v2 
checka = refl

checkb : lnf (lnf t1) ≡ lnf t1
checkb = refl

check1 : lnf (fst₀ t1) ≡ v1
check1 = refl

check2 : lnf (snd₀ t1) ≡ v2
check2 = refl

a : 𝓛 ( ( ( (B0 ⇒ B0) ⇒ (B0 ⇒ B0) ) ⇒ ( (B0 ⇒ B0) ⇒ (B0 ⇒ B0) ) ) ) ·
a = abs (var •)

B1 : 𝓣
B1 = B0 ⋆ B0

b : 𝓛 ( ( ( (B1 ⇒ B1) ⇒ (B1 ⇒ B1) ) ⇒ ( (B1 ⇒ B1) ⇒ (B1 ⇒ B1) ) ) ⇒ ( ( (B1 ⇒ B1) ⇒ (B1 ⇒ B1) ) ⇒ ( (B1 ⇒ B1) ⇒ (B1 ⇒ B1) ) ) ) ·
b = abs (var •)

\end{code}
