-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelCore where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsCore

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsCore.Ident -> Result
transIdent x = case x of
  AbsCore.Ident string -> failure x

transCaseTk :: AbsCore.CaseTk -> Result
transCaseTk x = case x of
  AbsCore.CaseTk string -> failure x

transDataTk :: AbsCore.DataTk -> Result
transDataTk x = case x of
  AbsCore.DataTk string -> failure x

transExp :: AbsCore.Exp -> Result
transExp x = case x of
  AbsCore.ELam patt exp -> failure x
  AbsCore.ESet -> failure x
  AbsCore.EPi patt exp1 exp2 -> failure x
  AbsCore.ESig patt exp1 exp2 -> failure x
  AbsCore.EOne -> failure x
  AbsCore.Eunit -> failure x
  AbsCore.EPair exp1 exp2 -> failure x
  AbsCore.ECon ident exp -> failure x
  AbsCore.EData datatk summands -> failure x
  AbsCore.ECase casetk branchs -> failure x
  AbsCore.EFst exp -> failure x
  AbsCore.ESnd exp -> failure x
  AbsCore.EApp exp1 exp2 -> failure x
  AbsCore.EVar ident -> failure x
  AbsCore.EVoid -> failure x
  AbsCore.EDec decl exp -> failure x
  AbsCore.EPN -> failure x

transDecl :: AbsCore.Decl -> Result
transDecl x = case x of
  AbsCore.Def patt exp1 exp2 -> failure x
  AbsCore.Drec patt exp1 exp2 -> failure x

transPatt :: AbsCore.Patt -> Result
transPatt x = case x of
  AbsCore.PPair patt1 patt2 -> failure x
  AbsCore.Punit -> failure x
  AbsCore.PVar ident -> failure x

transSummand :: AbsCore.Summand -> Result
transSummand x = case x of
  AbsCore.Summand ident exp -> failure x

transBranch :: AbsCore.Branch -> Result
transBranch x = case x of
  AbsCore.Branch ident exp -> failure x
