-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language CTTv1.

module CTTv.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Term
    = TDef Ident Term Term Term
    | Abst Ident Term Term
    | Sum Term Term
    | Sigma Ident Term Term
    | Pair Term Term
    | Partial DisjFormula Term
    | Restr System Term
    | App Term Term
    | Ind Term Term Term Term
    | Comp Term DisjFormula Term Term Term Term
    | Succ Term
    | InL Term
    | InR Term
    | Split Term Term Term Term
    | Var Ident
    | Universe
    | Nat
    | Zero
    | I
    | Fst Term
    | Snd Term
    | Sys System
    | I0
    | I1
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Toplevel
    = Definition Ident Term Term
    | Declaration Ident Term
    | Example Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AtomicFormula = Eq0 Ident | Eq1 Ident | Diag Ident Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConjFormula = Conj [AtomicFormula]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DisjFormula = Disj [ConjFormula]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SysElem = SysElem ConjFormula Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data System = System [SysElem]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Program = Program [Toplevel]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

arr :: Term -> Term -> Term
arr = \ e1 e2 -> Abst (Ident "") e1 e2

abstn :: [Ident] -> Term -> Term -> Term
abstn = \ vs t1 t2 -> abstn vs t1 t2

prod :: Term -> Term -> Term
prod = \ e1 e2 -> Sigma (Ident "") e1 e2

sigman :: [Ident] -> Term -> Term -> Term
sigman = \ vs e1 e2 -> sigman vs e1 e2

comp0 :: Term -> Term -> Term -> Term -> Term -> Term
comp0 = \ e2 e5 e6 e7 e8 -> Comp e2 (Disj []) e5 e6 e7 e8

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

