-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module CTTv.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified CTTv.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: CTTv.Abs.Ident -> Result
transIdent x = case x of
  CTTv.Abs.Ident string -> failure x

transTerm :: CTTv.Abs.Term -> Result
transTerm x = case x of
  CTTv.Abs.TDef ident term1 term2 term3 -> failure x
  CTTv.Abs.Abst ident term1 term2 -> failure x
  CTTv.Abs.Sum term1 term2 -> failure x
  CTTv.Abs.Sigma ident term1 term2 -> failure x
  CTTv.Abs.Pair term1 term2 -> failure x
  CTTv.Abs.Partial disjformula term -> failure x
  CTTv.Abs.Restr system term -> failure x
  CTTv.Abs.App term1 term2 -> failure x
  CTTv.Abs.Ind term1 term2 term3 term4 -> failure x
  CTTv.Abs.Comp term1 disjformula term2 term3 term4 term5 -> failure x
  CTTv.Abs.Succ term -> failure x
  CTTv.Abs.InL term -> failure x
  CTTv.Abs.InR term -> failure x
  CTTv.Abs.Split term1 term2 term3 term4 -> failure x
  CTTv.Abs.Var ident -> failure x
  CTTv.Abs.Universe -> failure x
  CTTv.Abs.Nat -> failure x
  CTTv.Abs.Zero -> failure x
  CTTv.Abs.I -> failure x
  CTTv.Abs.Fst term -> failure x
  CTTv.Abs.Snd term -> failure x
  CTTv.Abs.Sys system -> failure x
  CTTv.Abs.I0 -> failure x
  CTTv.Abs.I1 -> failure x

transToplevel :: CTTv.Abs.Toplevel -> Result
transToplevel x = case x of
  CTTv.Abs.Definition ident term1 term2 -> failure x
  CTTv.Abs.Declaration ident term -> failure x
  CTTv.Abs.Example term -> failure x

transAtomicFormula :: CTTv.Abs.AtomicFormula -> Result
transAtomicFormula x = case x of
  CTTv.Abs.Eq0 ident -> failure x
  CTTv.Abs.Eq1 ident -> failure x
  CTTv.Abs.Diag ident1 ident2 -> failure x

transConjFormula :: CTTv.Abs.ConjFormula -> Result
transConjFormula x = case x of
  CTTv.Abs.Conj atomicformulas -> failure x

transDisjFormula :: CTTv.Abs.DisjFormula -> Result
transDisjFormula x = case x of
  CTTv.Abs.Disj conjformulas -> failure x

transSysElem :: CTTv.Abs.SysElem -> Result
transSysElem x = case x of
  CTTv.Abs.SysElem conjformula term -> failure x

transSystem :: CTTv.Abs.System -> Result
transSystem x = case x of
  CTTv.Abs.System syselems -> failure x

transProgram :: CTTv.Abs.Program -> Result
transProgram x = case x of
  CTTv.Abs.Program toplevels -> failure x
