-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Lam.

module AbsLam where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Expr
    = Ann Expr Ty
    | Lambda Name Expr
    | Add1 Expr
    | App Expr Expr
    | Rec Ty Expr Expr Expr
    | Var Name
    | Zero
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Ty = TArr Ty Ty | TNat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Name = Name String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

