-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLam where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLam

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transName :: AbsLam.Name -> Result
transName x = case x of
  AbsLam.Name string -> failure x

transExpr :: AbsLam.Expr -> Result
transExpr x = case x of
  AbsLam.Ann expr ty -> failure x
  AbsLam.Lambda name expr -> failure x
  AbsLam.Add1 expr -> failure x
  AbsLam.App expr1 expr2 -> failure x
  AbsLam.Rec ty expr1 expr2 expr3 -> failure x
  AbsLam.Var name -> failure x
  AbsLam.Zero -> failure x

transTy :: AbsLam.Ty -> Result
transTy x = case x of
  AbsLam.TArr ty1 ty2 -> failure x
  AbsLam.TNat -> failure x
