-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language cubical.

module Cubical.Abs where

--import Prelude (String, foldr)
import Prelude
import qualified Prelude as C (Eq(..), Ord, Show(..), Read)
import qualified Data.String
--import Data.List (intercalate,delete)
import Data.List (intercalate)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Read, Data.String.IsString)

instance C.Show Ident where
  show (Ident s) = s


data Term
    = TDef Ident Term Term Term
    | Abst Ident Term Term
    | Sum Term Term
    | Sigma Ident Term Term
    | Pair Term Term
    | Partial DisjFormula Term
    | Restr System Term
    | App Term Term
    | Ind Term Term Term Term
    | Comp Term DisjFormula Term Term Term Term
    | Succ Term
    | InL Term
    | InR Term
    | Split Term Term Term Term
    | Var Ident
    | Universe
    | Nat
    | Zero
    | I
    | Fst Term
    | Snd Term
    | Sys System
    | I0
    | I1
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Toplevel
    = Definition Ident Term Term
    | Declaration Ident Term
    | Example Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AtomicFormula = Eq0 Ident | Eq1 Ident | Diag Ident Ident
  deriving (C.Ord, C.Read)

-- Equality between atomic formulas
instance C.Eq AtomicFormula where
  af1 == af2 = case (af1,af2) of
    (Eq0 s1,Eq0 s2) -> s1 == s2
    (Eq1 s1,Eq1 s2) -> s1 == s2
    (Diag s1 s2,Diag s3 s4) -> (s1 == s3 && s2 == s4) || (s1 == s4 && s2 == s3)
    otherwise -> False

data ConjFormula = Conj [AtomicFormula]
  deriving (C.Eq, C.Ord, C.Read)

data DisjFormula = Disj [ConjFormula]
  deriving (C.Eq, C.Ord, C.Read)

instance C.Show AtomicFormula where
  show af = case af of
    Eq0 s -> show s ++ " = 0"
    Eq1 s -> show s ++ " = 1"
    Diag s1 s2 -> show s1 ++ " = " ++ show s2

instance Show ConjFormula where
  show (Conj cf)
    | null cf = "True"
    | otherwise = intercalate " /\\ " (map show cf)

instance Show DisjFormula where
  show disj@(Disj df)
    | disj == fFalse = "False"
    | disj == fTrue = "True"
    | otherwise = intercalate " \\/ " $
      map (\cf -> "(" ++ show cf ++ ")") df

-- True (disjunctive) formula: just one empty conjunction
fTrue :: DisjFormula
fTrue = Disj [Conj []]
-- False formula: empty disjunction
fFalse :: DisjFormula
fFalse = Disj []


data SysElem = SysElem ConjFormula Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data System = System [SysElem]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Program = Program [Toplevel]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

arr :: Term -> Term -> Term
arr = \ e1 e2 -> Abst (Ident "") e1 e2

abstn :: Ident -> [Ident] -> Term -> Term -> Term
abstn = \ v vs e1 e2 -> Abst v e1 (foldr (\i e -> Abst i e1 e) e2 vs)

prod :: Term -> Term -> Term
prod = \ e1 e2 -> Sigma (Ident "") e1 e2

sigman :: Ident -> [Ident] -> Term -> Term -> Term
sigman = \ v vs e1 e2 -> Sigma v e1 (foldr (\i e -> Sigma i e1 e) e2 vs)

comp0 :: Term -> Term -> Term -> Term -> Term -> Term
comp0 = \ e2 e5 e6 e7 e8 -> Comp e2 (Disj []) e5 e6 e7 e8
