-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Cubical.

module Cubical.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Cubical.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Cubical.Abs.Ident where
  prt _ (Cubical.Abs.Ident i) = doc $ showString i
instance Print Cubical.Abs.Term where
  prt i = \case
    Cubical.Abs.TDef id_ term1 term2 term3 -> prPrec i 0 (concatD [doc (showString "["), prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString "="), prt 0 term2, doc (showString "]"), prt 0 term3])
    Cubical.Abs.Abst id_ term1 term2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString "]"), prt 0 term2])
    Cubical.Abs.Sum term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString "+"), prt 1 term2])
    Cubical.Abs.Sigma id_ term1 term2 -> prPrec i 1 (concatD [doc (showString "<"), prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString ">"), prt 0 term2])
    Cubical.Abs.Pair term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString ","), prt 2 term2])
    Cubical.Abs.Partial disjformula term -> prPrec i 1 (concatD [doc (showString "["), prt 0 disjformula, doc (showString "]"), prt 1 term])
    Cubical.Abs.Restr system term -> prPrec i 1 (concatD [prt 0 system, prt 1 term])
    Cubical.Abs.App term1 term2 -> prPrec i 2 (concatD [prt 2 term1, prt 3 term2])
    Cubical.Abs.Ind term1 term2 term3 term4 -> prPrec i 2 (concatD [doc (showString "ind"), prt 3 term1, prt 3 term2, prt 3 term3, prt 3 term4])
    Cubical.Abs.Comp term1 disjformula term2 term3 term4 term5 -> prPrec i 2 (concatD [doc (showString "comp"), prt 3 term1, doc (showString "("), prt 0 disjformula, doc (showString ")"), prt 3 term2, prt 3 term3, prt 3 term4, prt 3 term5])
    Cubical.Abs.Succ term -> prPrec i 2 (concatD [doc (showString "S"), prt 3 term])
    Cubical.Abs.InL term -> prPrec i 2 (concatD [doc (showString "inl"), prt 3 term])
    Cubical.Abs.InR term -> prPrec i 2 (concatD [doc (showString "inr"), prt 3 term])
    Cubical.Abs.Split term1 term2 term3 term4 -> prPrec i 2 (concatD [doc (showString "split"), prt 3 term1, prt 3 term2, prt 3 term3, prt 3 term4])
    Cubical.Abs.Var id_ -> prPrec i 3 (concatD [prt 0 id_])
    Cubical.Abs.Universe -> prPrec i 3 (concatD [doc (showString "U")])
    Cubical.Abs.Nat -> prPrec i 3 (concatD [doc (showString "N")])
    Cubical.Abs.Zero -> prPrec i 3 (concatD [doc (showString "Z")])
    Cubical.Abs.I -> prPrec i 3 (concatD [doc (showString "I")])
    Cubical.Abs.Fst term -> prPrec i 3 (concatD [prt 3 term, doc (showString ".1")])
    Cubical.Abs.Snd term -> prPrec i 3 (concatD [prt 3 term, doc (showString ".2")])
    Cubical.Abs.Sys system -> prPrec i 3 (concatD [prt 0 system])
    Cubical.Abs.I0 -> prPrec i 3 (concatD [doc (showString "0")])
    Cubical.Abs.I1 -> prPrec i 3 (concatD [doc (showString "1")])

instance Print [Cubical.Abs.Ident] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Cubical.Abs.Toplevel where
  prt i = \case
    Cubical.Abs.Definition id_ term1 term2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString "="), prt 0 term2])
    Cubical.Abs.Declaration id_ term -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 term])
    Cubical.Abs.Example term -> prPrec i 0 (concatD [prt 0 term])

instance Print Cubical.Abs.AtomicFormula where
  prt i = \case
    Cubical.Abs.Eq0 id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), doc (showString "0")])
    Cubical.Abs.Eq1 id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), doc (showString "1")])
    Cubical.Abs.Diag id_1 id_2 -> prPrec i 0 (concatD [prt 0 id_1, doc (showString "="), prt 0 id_2])

instance Print Cubical.Abs.ConjFormula where
  prt i = \case
    Cubical.Abs.Conj atomicformulas -> prPrec i 0 (concatD [prt 0 atomicformulas])

instance Print [Cubical.Abs.AtomicFormula] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "/\\"), prt 0 xs]

instance Print Cubical.Abs.DisjFormula where
  prt i = \case
    Cubical.Abs.Disj conjformulas -> prPrec i 0 (concatD [prt 0 conjformulas])

instance Print [Cubical.Abs.ConjFormula] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "\\/"), prt 0 xs]

instance Print Cubical.Abs.SysElem where
  prt i = \case
    Cubical.Abs.SysElem conjformula term -> prPrec i 0 (concatD [prt 0 conjformula, doc (showString "->"), prt 0 term])

instance Print Cubical.Abs.System where
  prt i = \case
    Cubical.Abs.System syselems -> prPrec i 0 (concatD [doc (showString "["), prt 0 syselems, doc (showString "]")])

instance Print [Cubical.Abs.SysElem] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print Cubical.Abs.Program where
  prt i = \case
    Cubical.Abs.Program toplevels -> prPrec i 0 (concatD [prt 0 toplevels])

instance Print [Cubical.Abs.Toplevel] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]
