-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Cubical.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Cubical.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Cubical.Abs.Ident -> Result
transIdent x = case x of
  Cubical.Abs.Ident string -> failure x

transTerm :: Cubical.Abs.Term -> Result
transTerm x = case x of
  Cubical.Abs.TDef ident term1 term2 term3 -> failure x
  Cubical.Abs.Abst ident term1 term2 -> failure x
  Cubical.Abs.Sum term1 term2 -> failure x
  Cubical.Abs.Sigma ident term1 term2 -> failure x
  Cubical.Abs.Pair term1 term2 -> failure x
  Cubical.Abs.Partial disjformula term -> failure x
  Cubical.Abs.Restr system term -> failure x
  Cubical.Abs.App term1 term2 -> failure x
  Cubical.Abs.Ind term1 term2 term3 term4 -> failure x
  Cubical.Abs.Comp term1 disjformula term2 term3 term4 term5 -> failure x
  Cubical.Abs.Succ term -> failure x
  Cubical.Abs.InL term -> failure x
  Cubical.Abs.InR term -> failure x
  Cubical.Abs.Split term1 term2 term3 term4 -> failure x
  Cubical.Abs.Var ident -> failure x
  Cubical.Abs.Universe -> failure x
  Cubical.Abs.Nat -> failure x
  Cubical.Abs.Zero -> failure x
  Cubical.Abs.I -> failure x
  Cubical.Abs.Fst term -> failure x
  Cubical.Abs.Snd term -> failure x
  Cubical.Abs.Sys system -> failure x
  Cubical.Abs.I0 -> failure x
  Cubical.Abs.I1 -> failure x

transToplevel :: Cubical.Abs.Toplevel -> Result
transToplevel x = case x of
  Cubical.Abs.Definition ident term1 term2 -> failure x
  Cubical.Abs.Declaration ident term -> failure x
  Cubical.Abs.Example term -> failure x

transAtomicFormula :: Cubical.Abs.AtomicFormula -> Result
transAtomicFormula x = case x of
  Cubical.Abs.Eq0 ident -> failure x
  Cubical.Abs.Eq1 ident -> failure x
  Cubical.Abs.Diag ident1 ident2 -> failure x

transConjFormula :: Cubical.Abs.ConjFormula -> Result
transConjFormula x = case x of
  Cubical.Abs.Conj atomicformulas -> failure x

transDisjFormula :: Cubical.Abs.DisjFormula -> Result
transDisjFormula x = case x of
  Cubical.Abs.Disj conjformulas -> failure x

transSysElem :: Cubical.Abs.SysElem -> Result
transSysElem x = case x of
  Cubical.Abs.SysElem conjformula term -> failure x

transSystem :: Cubical.Abs.System -> Result
transSystem x = case x of
  Cubical.Abs.System syselems -> failure x

transProgram :: Cubical.Abs.Program -> Result
transProgram x = case x of
  Cubical.Abs.Program toplevels -> failure x
