-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelCTTv where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsCTTv

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsCTTv.Ident -> Result
transIdent x = case x of
  AbsCTTv.Ident string -> failure x

transTerm :: AbsCTTv.Term -> Result
transTerm x = case x of
  AbsCTTv.TDef ident term1 term2 term3 -> failure x
  AbsCTTv.Abst ident term1 term2 -> failure x
  AbsCTTv.Abstn idents term1 term2 -> failure x
  AbsCTTv.Sum term1 term2 -> failure x
  AbsCTTv.Sigma ident term1 term2 -> failure x
  AbsCTTv.Sigman idents term1 term2 -> failure x
  AbsCTTv.Partial disjformula term -> failure x
  AbsCTTv.Restr system term -> failure x
  AbsCTTv.Pair term1 term2 -> failure x
  AbsCTTv.App term1 term2 -> failure x
  AbsCTTv.Ind term1 term2 term3 term4 -> failure x
  AbsCTTv.Comp term1 disjformula term2 term3 term4 term5 -> failure x
  AbsCTTv.Comp0 term1 term2 term3 term4 term5 -> failure x
  AbsCTTv.Succ term -> failure x
  AbsCTTv.InL term -> failure x
  AbsCTTv.InR term -> failure x
  AbsCTTv.Split term1 term2 term3 term4 -> failure x
  AbsCTTv.Var ident -> failure x
  AbsCTTv.Universe -> failure x
  AbsCTTv.Nat -> failure x
  AbsCTTv.Zero -> failure x
  AbsCTTv.I -> failure x
  AbsCTTv.Fst -> failure x
  AbsCTTv.Snd -> failure x
  AbsCTTv.Sys system -> failure x
  AbsCTTv.I0 -> failure x
  AbsCTTv.I1 -> failure x

transToplevel :: AbsCTTv.Toplevel -> Result
transToplevel x = case x of
  AbsCTTv.Definition ident term1 term2 -> failure x
  AbsCTTv.Declaration ident term -> failure x
  AbsCTTv.Example term -> failure x

transAtomicFormula :: AbsCTTv.AtomicFormula -> Result
transAtomicFormula x = case x of
  AbsCTTv.Eq0 ident -> failure x
  AbsCTTv.Eq1 ident -> failure x
  AbsCTTv.Diag ident1 ident2 -> failure x

transConjFormula :: AbsCTTv.ConjFormula -> Result
transConjFormula x = case x of
  AbsCTTv.Conj atomicformulas -> failure x

transDisjFormula :: AbsCTTv.DisjFormula -> Result
transDisjFormula x = case x of
  AbsCTTv.Disj conjformulas -> failure x

transSysElem :: AbsCTTv.SysElem -> Result
transSysElem x = case x of
  AbsCTTv.SysElem conjformula term -> failure x

transSystem :: AbsCTTv.System -> Result
transSystem x = case x of
  AbsCTTv.System syselems -> failure x

transProgram :: AbsCTTv.Program -> Result
transProgram x = case x of
  AbsCTTv.Program toplevels -> failure x
