-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Core.

module Core.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Exp
    = ELam Patt Exp
    | ESet
    | EPi Patt Exp Exp
    | ESig Patt Exp Exp
    | EOne
    | Eunit
    | EPair Exp Exp
    | ECon Ident Exp
    | ESum [Summand]
    | EFun [Branch]
    | EFst Exp
    | ESnd Exp
    | EApp Exp Exp
    | EVar Ident
    | EVoid
    | EDec Decl Exp
    | EPN
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl = Def Patt Exp Exp | Drec Patt Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Patt = PPair Patt Patt | Punit | PVar Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Summand = Summand Ident Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Branch = Branch Ident Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

eArrow :: Exp -> Exp -> Exp
eArrow = \ a b -> EPi Punit a b

eTimes :: Exp -> Exp -> Exp
eTimes = \ a b -> ESig Punit a b

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

