-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelUntyped where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsUntyped

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsUntyped.Ident -> Result
transIdent x = case x of
  AbsUntyped.Ident string -> failure x

transExp :: AbsUntyped.Exp -> Result
transExp x = case x of
  AbsUntyped.Lam0 ident exp -> failure x
  AbsUntyped.App0 exp1 exp2 -> failure x
  AbsUntyped.Var0 ident -> failure x
