-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module CTT.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified CTT.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: CTT.Abs.Ident -> Result
transIdent x = case x of
  CTT.Abs.Ident string -> failure x

transTerm :: CTT.Abs.Term -> Result
transTerm x = case x of
  CTT.Abs.TDef ident term1 term2 term3 -> failure x
  CTT.Abs.Abst ident term1 term2 -> failure x
  CTT.Abs.Sum term1 term2 -> failure x
  CTT.Abs.Sigma ident term1 term2 -> failure x
  CTT.Abs.Pair term1 term2 -> failure x
  CTT.Abs.Partial disjformula term -> failure x
  CTT.Abs.Restr system term -> failure x
  CTT.Abs.App term1 term2 -> failure x
  CTT.Abs.Ind term1 term2 term3 term4 -> failure x
  CTT.Abs.Comp term1 disjformula term2 term3 term4 term5 -> failure x
  CTT.Abs.Succ term -> failure x
  CTT.Abs.InL term -> failure x
  CTT.Abs.InR term -> failure x
  CTT.Abs.Split term1 term2 term3 term4 -> failure x
  CTT.Abs.Var ident -> failure x
  CTT.Abs.Universe -> failure x
  CTT.Abs.Nat -> failure x
  CTT.Abs.Zero -> failure x
  CTT.Abs.I -> failure x
  CTT.Abs.Fst term -> failure x
  CTT.Abs.Snd term -> failure x
  CTT.Abs.Sys system -> failure x
  CTT.Abs.I0 -> failure x
  CTT.Abs.I1 -> failure x

transToplevel :: CTT.Abs.Toplevel -> Result
transToplevel x = case x of
  CTT.Abs.Definition ident term1 term2 -> failure x
  CTT.Abs.Declaration ident term -> failure x
  CTT.Abs.Example term -> failure x

transAtomicFormula :: CTT.Abs.AtomicFormula -> Result
transAtomicFormula x = case x of
  CTT.Abs.Eq0 ident -> failure x
  CTT.Abs.Eq1 ident -> failure x
  CTT.Abs.Diag ident1 ident2 -> failure x

transConjFormula :: CTT.Abs.ConjFormula -> Result
transConjFormula x = case x of
  CTT.Abs.Conj atomicformulas -> failure x

transDisjFormula :: CTT.Abs.DisjFormula -> Result
transDisjFormula x = case x of
  CTT.Abs.Disj conjformulas -> failure x

transSysElem :: CTT.Abs.SysElem -> Result
transSysElem x = case x of
  CTT.Abs.SysElem conjformula term -> failure x

transSystem :: CTT.Abs.System -> Result
transSystem x = case x of
  CTT.Abs.System syselems -> failure x

transProgram :: CTT.Abs.Program -> Result
transProgram x = case x of
  CTT.Abs.Program toplevels -> failure x
