-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelSimplyTyped where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsSimplyTyped

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsSimplyTyped.Ident -> Result
transIdent x = case x of
  AbsSimplyTyped.Ident string -> failure x

transExp :: AbsSimplyTyped.Exp -> Result
transExp x = case x of
  AbsSimplyTyped.Lam0 ident type_ exp -> failure x
  AbsSimplyTyped.App0 exp1 exp2 -> failure x
  AbsSimplyTyped.Var0 ident -> failure x

transType :: AbsSimplyTyped.Type -> Result
transType x = case x of
  AbsSimplyTyped.Base -> failure x
  AbsSimplyTyped.Arrow type_1 type_2 -> failure x
