-- File generated by the BNF Converter (bnfc 2.9.6).

-- | The abstract syntax of language DB.

module AbsDB where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Term = DBLam Term | DBApp Term Term | DBVar Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

