-- File generated by the BNF Converter (bnfc 2.9.6).

-- | The abstract syntax of language Lam.

module AbsLam where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Preterm
    = Lam Integer Preterm | App Preterm Preterm | Var Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

