-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLam where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLam

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transPreterm :: AbsLam.Preterm -> Result
transPreterm x = case x of
  AbsLam.Lam integer preterm -> failure x
  AbsLam.App preterm1 preterm2 -> failure x
  AbsLam.Var integer -> failure x
