-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelDB where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsDB

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transTerm :: AbsDB.Term -> Result
transTerm x = case x of
  AbsDB.DBLam term -> failure x
  AbsDB.DBApp term1 term2 -> failure x
  AbsDB.DBVar integer -> failure x
