-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Core.

module Core.Abs where

import Prelude (String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Int, Maybe(..)
  )

data Context = Ctx [Decl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = U
    | Var Ref
    | SVar Ref [Exp] Id
    | App Exp Exp
    | Arr Exp Exp
    | Abs Id Exp Exp
    | Let Id Exp Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl
    = Dec Id Exp | Def Id Exp Exp | Seg Id [Decl] | SInst Id Ref [Exp]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Ref = Rid Id | Rns Ref Id
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Id = Id ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Id where
  hasPosition (Id (p, _)) = C.Just p

