-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Core.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Core.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: Core.Abs.Id -> Result
transId x = case x of
  Core.Abs.Id string -> failure x

transContext :: Core.Abs.Context -> Result
transContext x = case x of
  Core.Abs.Ctx decls -> failure x

transExp :: Core.Abs.Exp -> Result
transExp x = case x of
  Core.Abs.U -> failure x
  Core.Abs.Var ref -> failure x
  Core.Abs.SVar ref exps id -> failure x
  Core.Abs.App exp1 exp2 -> failure x
  Core.Abs.Arr exp1 exp2 -> failure x
  Core.Abs.Abs id exp1 exp2 -> failure x
  Core.Abs.Let id exp1 exp2 exp3 -> failure x

transDecl :: Core.Abs.Decl -> Result
transDecl x = case x of
  Core.Abs.Dec id exp -> failure x
  Core.Abs.Def id exp1 exp2 -> failure x
  Core.Abs.Seg id decls -> failure x
  Core.Abs.SInst id ref exps -> failure x

transRef :: Core.Abs.Ref -> Result
transRef x = case x of
  Core.Abs.Rid id -> failure x
  Core.Abs.Rns ref id -> failure x
