----------------------------------------------------------
-- Expressions
--    This is a separate module generated by BNF converter
-----------------------------------------------------------

{- Core/Abs.hs 
module Core.Abs where

-- Haskell module generated by the BNF converter

newtype Ident = Ident String deriving (Eq,Ord,Show)
newtype CaseTk = CaseTk ((Int,Int),String) deriving (Eq,Ord,Show)
newtype DataTk = DataTk ((Int,Int),String) deriving (Eq,Ord,Show)
data Exp =
   ELam Patt Exp
 | ESet
 | EPi Patt Exp Exp
 | ESig Patt Exp Exp
 | EOne
 | Eunit
 | EPair Exp Exp
 | ECon Ident Exp
 | EData DataTk [Summand]
 | ECase CaseTk [Branch]
 | EFst Exp
 | ESnd Exp
 | EApp Exp Exp
 | EVar Ident
 | EVoid
 | EDec Decl Exp
 | EPN
  deriving (Eq,Ord,Show)

data Decl =
   Def Patt Exp Exp
 | Drec Patt Exp Exp
  deriving (Eq,Ord,Show)

data Patt =
   PPair Patt Patt
 | Punit
 | PVar Ident
  deriving (Eq,Ord,Show)

data Summand =
   Summand Ident Exp
  deriving (Eq,Ord,Show)

data Branch =
   Branch Ident Exp
  deriving (Eq,Ord,Show)

-}

-----------------------------------------
-- Main module
-----------------------------------------

{-# OPTIONS_GHC -Wall #-}

module Main where

import Prelude hiding ((*))
import System.Environment
import System.IO.Unsafe

import Core.Abs
import Core.Print
import Core.ErrM
import Core.Par

-----------------------------------------------------------
-- Values
-----------------------------------------------------------

type Name = Ident

data Val = -- u,v,t            
     Lam Clos           -- λf
  |  Pair Val Val       -- u,v
  |  Con Name Val       -- cv
  |  Unit               -- 0
  |  Set                -- U
  |  Pi  Val Clos       -- Πtg
  |  Sig Val Clos       -- Σtg
  |  One                -- 𝟙
  |  Fun  Pos SClos     -- fun s
  |  Data Pos SClos     -- Sum s
  |  Nt Neut            -- [k]
  deriving Show

data Neut = -- k
     Gen  Int Name        -- xₙ
  |  App  Neut Val        -- kv
  |  Fst  Neut            -- k.1
  |  Snd  Neut            -- k.2
  |  NtFun Pos SClos Neut -- sk
  deriving Show

type SClos = ([(Name,Exp)], Rho)  -- s ∷= ⟨S,ρ⟩
type   Nf  = Val
type TVal  = Val

----------------------------------------
-- Choice of function representations
----------------------------------------

-- Function closures
data Clos = -- f,g
     Cl Patt Exp Rho   -- ⟨λp.M,ρ⟩
  |  ClCmp Clos Name   -- f ∘ c
  deriving Show

-- instantiation of a closure by a value
-- inst ⟨λp.M,ρ⟩ v = ⇓M(ρ,p=v)
-- inst (f ∘ c)  v = inst f (c v)
(*) :: Clos -> Val -> Val
(Cl p e ρ) * v = eval e (UpVar ρ p v)
(ClCmp f c ) * v = f * Con c v

mkCl :: Patt -> Exp -> Rho -> Clos
mkCl p e ρ = Cl p e ρ

clCmp :: Clos -> Name -> Clos
clCmp g c  = ClCmp g c


{-
--  Higher order functions

type Clos = Val -> Val
instance Show Clos where show f = "Clos" ++ showVal 0 (Lam f)

(*) :: Clos -> Val -> Val
f * v = f v 

mkCl :: Patt -> Exp -> Rho -> Clos
mkCl p e rho = \v -> eval e (UpVar rho p v)

clCmp :: Clos -> Name -> Clos
clCmp g c = \v -> g * (Con c v)
-}

-------------------------------------
-- Operaions on Values
-------------------------------------

type Pos = ((Int, Int), String)

-- app (λf) v           = inst f v
-- app (fun⟨S,ρ⟩) (cᵢv) = app (⇓Mᵢρ) v
--                        where S=(c₁ → M₁ |⋯| cₙ → Mₙ)
-- app (fun s) [k]      = [sk]
-- app [k] v            = [kv]

app :: Val -> Val -> Val
app (Lam f)             v        = f * v
app (Fun _ (ces, rho)) (Con c v) = app (eval e rho) v
                                   where e = head [e' | (c',e') <- ces, c == c']
app (Fun pos s)        (Nt k)    = Nt(NtFun pos s k)
app (Nt k)             m         = Nt(App k m)
app w u = error ("app " ++ showVal 0 w ++ showVal 0 u)

vfst :: Val -> Val
vfst (Pair u1 _) = u1
vfst (Nt k)      = Nt(Fst k)
vfst w = error ("vfst " ++ showVal 0 w)

vsnd :: Val -> Val
vsnd (Pair _ u2) = u2
vsnd (Nt k)      = Nt(Snd k)
vsnd w =  error ("vsnd " ++ showVal 0 w)

---------------------------------------------
-- Environment
---------------------------------------------

data Rho =  -- ρ
     RNil                  -- ()
  |  UpVar Rho Patt Val    -- ρ,p=v
  |  UpDec Rho Decl        -- ρ,D
  deriving Show

getRho :: Rho -> Name -> Val
getRho (UpVar rho p v) x | x `inPat` p = patProj p x v
                         | otherwise   = getRho rho x
getRho (UpDec rho (Def  p _ e)) x | x `inPat` p = patProj p x (eval e rho)
                                  | otherwise   = getRho rho x
getRho rho0@(UpDec rho (Drec p _ e)) x
                                  | x `inPat` p = patProj p x (eval e rho0)
                                  | otherwise   = getRho rho x
getRho RNil _ = error "getRho"

inPat :: Name -> Patt -> Bool
inPat x (PVar y)      = x == y
inPat x (PPair p1 p2) = inPat x p1 || inPat x p2
inPat _ Punit         = False

patProj :: Patt -> Name -> Val -> Val
patProj (PVar y)      x v | x == y       = v
patProj (PPair p1 p2) x v | x `inPat` p1 = patProj p1 x (vfst v)
                          | x `inPat` p2 = patProj p2 x (vsnd v)
patProj _ _ _ = error "patProj"

lRho :: Rho -> Int
lRho RNil            = 0
lRho (UpVar ρ _ _) = lRho ρ + 1
lRho (UpDec ρ _  ) = lRho ρ


eval :: Exp -> Rho -> Val
eval e0 ρ = case e0 of
    ESet          -> Set                          -- ⇓Uρ      = U
    EDec d e      -> eval e (UpDec ρ d)           -- ⇓D;Mρ    = ⇓M(ρ,D)
    ELam p e      -> Lam $ mkCl p e ρ             -- ⇓λp.Mρ   = ⟨λp.M,ρ⟩
    EPi  p a b    -> Pi  (eval a ρ) $ mkCl p b ρ  -- ⇓Πp:A.Bρ = Π(⇓Aρ)⟨λp.B,ρ⟩
    ESig p a b    -> Sig (eval a ρ) $ mkCl p b ρ  -- ⇓Σp:A.Bρ = Σ(⇓Aρ)⟨λp.B,ρ⟩
    EOne          -> One                          -- ⇓𝟙ρ      = 𝟙
    Eunit         -> Unit                         -- ⇓0ρ      = 0
    EFst e        -> vfst (eval e ρ)              -- ⇓M.1ρ    = (⇓Mρ).1
    ESnd e        -> vsnd (eval e ρ)              -- ⇓M.2ρ    = (⇓Mρ).2
    EApp e1 e2    -> app (eval e1 ρ) (eval e2 ρ)  -- ⇓MNρ     = app (⇓Mρ) (⇓Nρ)
    EVar x        -> getRho ρ x                   -- ⇓xρ      = ρ(x)
    EPair e1 e2   -> Pair  (eval e1 ρ) (eval e2 ρ)-- ⇓M,Nρ    = (⇓Mρ,⇓Nρ)
    ECon c e1     -> Con c (eval e1 ρ)            -- ⇓cMρ     = c(⇓Mρ)
    EData (DataTk pos) cas                        -- ⇓Sum S ρ = Sum⟨S,ρ⟩
                  -> Data pos ([(c,a) | Summand c a <- cas], ρ)
    ECase (CaseTk pos) ces                        -- ⇓fun S ρ = fun⟨S,ρ⟩
                  -> Fun  pos ([(c,e) | Branch  c e <- ces], ρ)
    e -> error $ "eval: should have been desugared\n e = " ++ printTree e
{-
-------------------------------------------
-- Readback functions
-------------------------------------------

eVar :: String -> Exp
eVar = EVar . Ident

rbV :: Int -> Val  -> Exp -- to do: change to Normal Expression

rbV i v0 = case v0 of
      Lam f      -> ELam (pat i) (rbV (i+1) (f * gen i))
      Pair u v   -> EPair (rbV i u) (rbV i v)
      Con  c v   -> ECon  c (rbV i v)
      Unit       -> Eunit 
      Set        -> ESet
      Pi  t g    -> EPi  (pat i) (rbV i t) (rbV (i+1) (g * gen i))
      Sig t g    -> ESig (pat i) (rbV i t) (rbV (i+1) (g * gen i))
      One        -> EOne
      Fun  pos (_,ρ) -> foldr (flip EApp) (eVar $ show pos) (rbRho i ρ)
      Data pos (_,ρ) -> foldr (flip EApp) (eVar $ show pos) (rbRho i ρ)
      Nt k       -> rbN i k
  where pat j = PVar $ Ident $ "G#" ++ show j
        gen j = Nt $ Gen j (Ident "G#")

rbN :: Int -> Neut -> Exp
rbN i k0 = case k0 of
      Gen j x -> eVar $ printTree x++show j
      App k m -> EApp (rbN i k) (rbV i m)
      Fst k   -> EFst (rbN i k)
      Snd k   -> ESnd (rbN i k)
      NtFun pos (_,ρ) k ->
        foldr (flip EApp) (eVar $ show pos) (rbRho i ρ) `EApp` rbN i k

rbRho :: Int -> Rho -> [Exp]
rbRho _ RNil = []
rbRho i (UpVar ρ _ v) = rbV i v : rbRho i ρ
rbRho i (UpDec ρ _  ) = rbRho i ρ

------------------------------------------------
-- Error monad
------------------------------------------------

type ErrorMessage = String
type G a = Either ErrorMessage a

------------------------------------------------
-- Type environment
------------------------------------------------

type Gamma = [(Name, TVal)]

lookupG :: (Show a, Eq a) => a -> [(a,b)] -> G b
lookupG x xts = case lookup x xts of Just t  -> return t
                                     Nothing -> fail $ "lookupG:" ++ show x

-- Updating type environment   Gamma |- p : t = u => Gamma'
upG :: Gamma -> Patt -> TVal -> Val -> G Gamma
upG gma Punit         _         _ = return gma
upG gma (PVar x)      t         _ = return $ (x,t):gma
upG gma (PPair p1 p2) (Sig t g) v = do gma1 <- upG gma p1 t (vfst v)
                                       upG gma1 p2 (g * vfst v) (vsnd v)
upG _   p             _         _ = fail $ "upG: p = " ++ printTree p

-------------------------------------------------
-- Type checking rules
-------------------------------------------------

genV :: Rho -> Val
genV ρ = Nt(Gen (lRho ρ) (Ident "TC#"))

checkD :: Rho -> Gamma -> Decl -> G Gamma
checkT :: Rho -> Gamma -> Exp  -> G ()
check  :: Rho -> Gamma -> Exp  -> TVal -> G ()
checkI :: Rho -> Gamma -> Exp  -> G TVal

checkD ρ gma d@(Def  p a e) = do
  debug $ "checking "++ printTree d
  checkT ρ gma a
  let t = eval a ρ
  check ρ gma e t
  gma1 <- upG gma p t (eval e ρ)
  return gma1
           
checkD ρ gma d@(Drec p a e) = do
  debug $ "checking "++ printTree d
  checkT ρ gma a
  let t   = eval a ρ
      gen = genV ρ
  gma1 <- upG gma p t gen
  check (UpVar ρ p gen) gma1 e t
  let v = eval e (UpDec ρ d)
  gma2 <- upG gma p t v
  return gma2

checkT ρ gma e0 =
  case e0 of
    EPi  p a b -> do checkT ρ gma a
                     gma1 <- upG gma p (eval a ρ) (genV ρ)
                     checkT (UpVar ρ p (genV ρ)) gma1 b
    ESig p a b -> checkT ρ gma (EPi p a b)
    ESet       -> return ()
    EOne       -> return ()
    a          -> check ρ gma a Set

check ρ gma e0 t0 = do
  case (e0, t0) of
    (ELam p e   , Pi  t g )-> do let gen = genV ρ
                                 gma1 <- upG gma p t gen
                                 check (UpVar ρ p gen) gma1 e (g * gen)
    (EPair e1 e2, Sig t g )-> do check ρ gma e1 t
                                 check ρ gma e2 (g * eval e1 ρ)
    (ECon c e   , Data _ (cas,ρ1))-> do a <- lookupG c cas
                                        check ρ gma e (eval a ρ1)
    (ECase _ ces, Pi (Data _ (cas, ρ1)) g)
      | cs == cs1 -> sequence_ [check ρ gma e (Pi (eval a ρ1) (clCmp g c))
                               | (Branch c e, (_,a)) <- zip ces cas]
      | otherwise -> fail "case branches does not match the data type"
      where cs  = [c | Branch c _ <- ces]
            cs1 = [c | (c, _)     <- cas]
    (Eunit      , One)-> return ()
    (EOne       , Set)-> return ()
    (EPi  p a b , Set)-> do check ρ gma a Set
                            let gen = genV ρ
                            gma1 <- upG gma p (eval a ρ) gen
                            check (UpVar ρ p gen) gma1 b Set
    (ESig p a b , Set)-> check ρ gma (EPi p a b) Set
    (EData _ cas, Set)-> sequence_ [check ρ gma a Set | Summand _ a <- cas]
    (EDec d e   , t  )-> do gma1 <- checkD ρ gma d
                            check (UpDec ρ d) gma1 e t
    (e          , t  )-> do t1 <- checkI ρ gma e
                            eqNf (lRho ρ) t t1
  where
  eqNf :: Int -> Nf -> Nf -> G ()
  eqNf i m1 m2
    | e1 == e2  = return ()
    | otherwise = fail $ "eqNf: " ++ printTree e1 ++ "=/=" ++ printTree e2
    where e1 = rbV i m1
          e2 = rbV i m2

checkI ρ gma e0 =
  case e0 of
    EVar x     -> lookupG x gma
    EApp e1 e2 -> do t1 <- checkI ρ gma e1
                     (t, g) <- extPiG t1
                     check ρ gma e2 t
                     return (g * eval e2 ρ)
    EFst e     -> fst `fmap` (extSigG =<< checkI ρ gma e)
    ESnd e     -> do t <- checkI ρ gma e
                     (_, g) <- extSigG t
                     return (g * vfst (eval e ρ))

    e          -> fail ("checkI: " ++ printTree e)
  where
  extPiG :: TVal -> G (TVal, Clos)
  extPiG (Pi t g) = return (t, g)
  extPiG u        = fail ("extPiG " ++ showVal 0 u)

  extSigG :: TVal -> G (TVal, Clos)
  extSigG (Sig t g) = return (t, g)
  extSigG u         = fail ("extSigG " ++ showVal 0 u)

------------------------------------------------------
-- Main checking routines
------------------------------------------------------

-- The input is checked as an expression of type One.
checkMain :: Exp -> G ()
checkMain e = check RNil [] e One

-- checking a string input
checkStr :: String -> IO()
checkStr s =
  case pExp $ myLexer s of -- parsing using routines generated by BNF converter
    Bad msg -> putStrLn $ "Parse error: " ++ msg
    Ok  e  -> do
      case checkMain e of
        Left  msg' -> putStrLn ("type-checking failed:\n" ++ msg')
        Right _    -> putStrLn ("type-checking succeded.")

-- checking the content of a file.
checkFile :: String -> IO()
checkFile file = checkStr =<< readFile file

-- main routine to execute at a command line.
main :: IO()
main = do args <- getArgs
          case args of [file] -> checkFile file
                       _      -> putStrLn "usage: agdacore FILE"

-----------------------------------------------------
-- For debugging
-----------------------------------------------------
debug :: String -> G ()
debug = \s -> do () <- return $ unsafePerformIO $ putStrLn s; return ()

showVal :: Int -> Val -> String  -- for debug print only
showVal i u = show (rbV i u)

-}

showVal :: Int -> Val -> String  -- for debug print only
showVal i u = show u
