-- File generated by the BNF Converter (bnfc 2.9.6).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelCoq where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsCoq

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: AbsCoq.Id -> Result
transId x = case x of
  AbsCoq.Id string -> failure x

transExp :: AbsCoq.Exp -> Result
transExp x = case x of
  AbsCoq.Let id exp1 exp2 exp3 -> failure x
  AbsCoq.Abs id exp -> failure x
  AbsCoq.Pi id exp1 exp2 -> failure x
  AbsCoq.App exp1 exp2 -> failure x
  AbsCoq.Type -> failure x
  AbsCoq.Var id -> failure x
