-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Cube.

module AbsCube where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Exp
    = Lam0 Ident Exp Exp
    | Pi0 Ident Exp Exp
    | Kind0 Kinds
    | App0 Exp Exp
    | Var0 Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Kinds = Star | Box
  deriving (C.Eq, C.Ord, C.Show, C.Read)

eArrow :: Exp -> Exp -> Exp
eArrow = \ a b -> Pi0 (Ident "_") a b

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

