-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelCube where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsCube

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsCube.Ident -> Result
transIdent x = case x of
  AbsCube.Ident string -> failure x

transExp :: AbsCube.Exp -> Result
transExp x = case x of
  AbsCube.Lam0 ident exp1 exp2 -> failure x
  AbsCube.Pi0 ident exp1 exp2 -> failure x
  AbsCube.Kind0 kinds -> failure x
  AbsCube.App0 exp1 exp2 -> failure x
  AbsCube.Var0 ident -> failure x

transKinds :: AbsCube.Kinds -> Result
transKinds x = case x of
  AbsCube.Star -> failure x
  AbsCube.Box -> failure x
